Name: Rex::Module::Database::Postgres::Admin
Description: Postgres Admin Module
Author: Paulo Graça <paulo.graca@fccn.pt>
License: GPLv3

# Only if you have dependencies to other Rex Modules.
Require:
   - Rex::Module::Database::Postgres
